version: '3.8'

services:
  backend:
    build:
      context: ./temp
      dockerfile: Dockerfile
    volumes:
      - "static:/app/static"
    env_file:
      - '.env'
    ports:
      - "8081:8081"
  nginx:
    build: ./nginx
    volumes:
      - 'static:/app/static'
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  static:
